name: ChatFilter
version: 3.0.0
main: InspectorGadget\ChatFilter\MainHandler
api: 3.0.0
author: InspectorGadget

commands:
  cf:
    permission: chatfilter.command

permissions:
  chatfilter:
    default: op
    description: "Chat Filter Root Permission"
    children:
      chatfilter.command:
        description: "Permission for Command"
      chatfilter.bypass:
        description: "To bypass the Filter!"