name: ChatFilter
version: 1.0.0
main: RTG\ChatFilter\Loader
api: 3.0.0-ALPHA8
author: IG

commands:
    cf:
        permission: chatfilter.command
permissions:
    chatfilter.command:
        default: op
